library = "libwidget"
version = "0.1.0"
source_origin = "bench_clang/charger/testlibs/libwidget"
source_hash = "ed2e8470b425f5fd"
dependencies = []
artifact = "libwidget.lib"
artifact_hash = "82a8ef9d75fa865b"
symbols = [
    "??0Widget@@QEAA@_J0@Z",
    "?area@Widget@@QEBA_JXZ",
    "?area@Widget@@QEBA_J_J@Z",
    "?get_x@Widget@@QEBA_JXZ",
    "?widget_new@@YAPEAVWidget@@_J0@Z",
    "?widget_move@@YAXPEAVWidget@@_J1@Z",
    "?widget_area@@YA_JPEAVWidget@@@Z",
    "?widget_get_x@@YA_JPEAVWidget@@@Z",
    "?widget_free@@YAXPEAVWidget@@@Z",
]

[abi]
os = "windows"
arch = "x86_64"
compiler = "clang"
compiler_version = "clang version 22.1.8 (https://github.com/llvm/llvm-project ca7933e47d3a3451d81e72ac174dcb5aa28b59d1)"
cxx_abi = "MSVC"
cxx_stdlib = "msvc"
build_flags = []
