library = "libc_common"
version = "0.1.0"
source_origin = "bench_clang/charger/testlibs/libc_common"
source_hash = "0195cd137d747ece"
dependencies = []
artifact = "libc_common.lib"
artifact_hash = "f83dd37c59d7a323"
symbols = ["common_add"]
cpp_vtable_classes = []
cpp_virtual_symbols = []
cpp_destructor_symbols = []

[abi]
os = "windows"
arch = "x86_64"
compiler = "clang"
compiler_version = "clang version 22.1.8 (https://github.com/llvm/llvm-project ca7933e47d3a3451d81e72ac174dcb5aa28b59d1)"
cxx_abi = "C"
cxx_stdlib = "-"
build_flags = []

[cpp_inheritance]

[cpp_template_instantiations]
