library = "libvariant"
version = "0.1.0"
source_origin = "bench_clang/charger/testlibs/libvariant"
source_hash = "9dabe505aeee2565"
dependencies = []
artifact = "libvariant.lib"
artifact_hash = "edfef8488adef4ef"
symbols = [
    "variant_set_int",
    "variant_as_float",
    "color_or",
    "get_max",
    "get_version",
]

[abi]
os = "windows"
arch = "x86_64"
compiler = "clang"
compiler_version = "clang version 22.1.8 (https://github.com/llvm/llvm-project ca7933e47d3a3451d81e72ac174dcb5aa28b59d1)"
cxx_abi = "C"
cxx_stdlib = "-"
build_flags = []
