library = "libcb"
version = "0.1.0"
source_origin = "bench_clang/charger/testlibs/libcb"
source_hash = "e626311be4e3e5e2"
dependencies = []
artifact = "libcb.lib"
artifact_hash = "28e4e6acdcec15e3"
symbols = [
    "register_mathops",
    "run_processor",
    "run_lifecycle",
    "install_and_run",
]

[abi]
os = "windows"
arch = "x86_64"
compiler = "clang"
compiler_version = "clang version 22.1.8 (https://github.com/llvm/llvm-project ca7933e47d3a3451d81e72ac174dcb5aa28b59d1)"
cxx_abi = "C"
cxx_stdlib = "-"
build_flags = []
