library = "libshape"
version = "0.1.0"
source_origin = "bench_clang/charger/testlibs/libshape"
source_hash = "0124a548fbcd0190"
dependencies = []
artifact = "libshape.lib"
artifact_hash = "e9cd1439bae43a36"
symbols = [
    "?area@Shape@@UEBA_JXZ",
    "??_DShape@@QEAAXXZ",
    "??4Shape@@QEAAAEAV0@AEBV0@@Z",
    "??0Shape@@QEAA@AEBV0@@Z",
    "??0Circle@@QEAA@_J@Z",
    "?area@Circle@@UEBA_JXZ",
    "??0Circle@@QEAA@AEBV0@@Z",
    "??0Circle@@QEAA@$$QEAV0@@Z",
    "??4Circle@@QEAAAEAV0@AEBV0@@Z",
    "??4Circle@@QEAAAEAV0@$$QEAV0@@Z",
    "??_DCircle@@QEAAXXZ",
    "??2@YAPEAX_K@Z",
    "??2@YAPEAX_KW4align_val_t@std@@@Z",
    "??_U@YAPEAX_K@Z",
    "??_U@YAPEAX_KW4align_val_t@std@@@Z",
    "??3@YAXPEAX@Z",
    "??3@YAXPEAXW4align_val_t@std@@@Z",
    "??3@YAXPEAX_K@Z",
    "??3@YAXPEAX_KW4align_val_t@std@@@Z",
    "??_V@YAXPEAX@Z",
    "??_V@YAXPEAXW4align_val_t@std@@@Z",
    "??_V@YAXPEAX_K@Z",
    "??_V@YAXPEAX_KW4align_val_t@std@@@Z",
    "?make_circle@@YAPEAVShape@@_J@Z",
    "?shape_area@@YA_JPEAVShape@@@Z",
    "?shape_free@@YAXPEAVShape@@@Z",
]
cpp_vtable_classes = [
    "Shape",
    "Circle",
]
cpp_virtual_symbols = [
    "?area@Shape@@UEBA_JXZ",
    "??_DShape@@QEAAXXZ",
]
cpp_destructor_symbols = [
    "??_DShape@@QEAAXXZ",
    "??_DCircle@@QEAAXXZ",
]

[abi]
os = "windows"
arch = "x86_64"
compiler = "clang"
compiler_version = "clang version 22.1.8 (https://github.com/llvm/llvm-project ca7933e47d3a3451d81e72ac174dcb5aa28b59d1)"
cxx_abi = "MSVC"
cxx_stdlib = "msvc"
build_flags = []

[cpp_inheritance]
Circle = ["Shape"]
