library = "libgvar"
version = "0.1.0"
source_origin = "bench_clang/charger/testlibs/libgvar"
source_hash = "8e189718782a09de"
dependencies = []
artifact = "libgvar.lib"
artifact_hash = "afe94a22506f09e2"
symbols = [
    "gvar_bump",
    "gvar_get_counter",
    "gvar_set_counter",
    "gvar_get_static",
    "gvar_set_msg",
    "gvar_get_msg",
    "gvar_get_origin_x",
    "gvar_set_origin",
    "gvar_sum_ints",
]

[abi]
os = "windows"
arch = "x86_64"
compiler = "clang"
compiler_version = "clang version 22.1.8 (https://github.com/llvm/llvm-project ca7933e47d3a3451d81e72ac174dcb5aa28b59d1)"
cxx_abi = "C"
cxx_stdlib = "-"
build_flags = []
