library = "libagg"
version = "0.1.0"
source_origin = "bench_clang/charger/testlibs/libagg"
source_hash = "c9cb2155b407b587"
dependencies = []
artifact = "libagg.lib"
artifact_hash = "35f6639048564d0d"
symbols = [
    "agg_origin_x",
    "agg_set_val",
    "agg_get_val",
    "agg_name_len",
    "flex_set",
    "flex_get",
    "flex_make",
]

[abi]
os = "windows"
arch = "x86_64"
compiler = "clang"
compiler_version = "clang version 22.1.8 (https://github.com/llvm/llvm-project ca7933e47d3a3451d81e72ac174dcb5aa28b59d1)"
cxx_abi = "C"
cxx_stdlib = "-"
build_flags = []
