library = "libstack"
version = "0.1.0"
source_origin = "bench_clang/charger/testlibs/libstack"
source_hash = "026afb3140d2244b"
dependencies = []
artifact = "libstack.lib"
artifact_hash = "7765d5d424d978ae"
symbols = [
    "Stack<T>",
    "~Stack<T>",
    "push",
    "pop",
    "size",
    "?make_stack@@YAPEAV?$Stack@_J@@XZ",
    "?stack_push@@YAXPEAV?$Stack@_J@@_J@Z",
    "?stack_size@@YA_JPEAV?$Stack@_J@@@Z",
    "?stack_free@@YAXPEAV?$Stack@_J@@@Z",
]
cpp_vtable_classes = []
cpp_virtual_symbols = []
cpp_destructor_symbols = ["~Stack<T>"]

[abi]
os = "windows"
arch = "x86_64"
compiler = "clang"
compiler_version = "clang version 22.1.8 (https://github.com/llvm/llvm-project ca7933e47d3a3451d81e72ac174dcb5aa28b59d1)"
cxx_abi = "MSVC"
cxx_stdlib = "msvc"
build_flags = []

[cpp_inheritance]

[cpp_template_instantiations]
Stack_long_long = ["long long"]
